

#ifndef GLOBALDEFINES
#define GLOBALDEFINES


#define MAX_MEASUREMENT_POINTS_PER_SITE     ( 10 )
#define MAX_MEASUREMENT_POINTS              ( MAX_MEASUREMENT_POINTS_PER_SITE*2 )


#endif // GLOBALDEFINES

